sudo: required #require super user
services:
  - docker #require a copy of docker

before_install: #what needs to be done before project run
  - docker build -t phuaweijie/docker-react -f ./client/Dockerfile.dev ./client

script: #what to run, most of the time we run all the test here if it fails, it will not proceed to the next step
  - docker run -e CI=true phuaweijie/docker-react npm run test

after_success: #what to do after success
  - docker build -t phuaweijie/multi-client ./client
  - docker build -t phuaweijie/multi-nginx ./nginx
  - docker build -t phuaweijie/multi-server ./server
  - docker build -t phuaweijie/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take image and push to docker hub
  - docker push phuaweijie/multi-client
  - docker push phuaweijie/multi-nginx
  - docker push phuaweijie/multi-server
  - docker push phuaweijie/multi-worker
